import { Card, Comment, Transaction } from "@/types/index";

export const initialCards: Card[] = [
  {
    id: "card-1",
    holderName: "Mark Henry",
    number: "4727856245672020",
    expiry: "12/20",
    cvv: "123",
    status: "active",
    network: "visa",
    availableBalance: 3000,
  },
  {
    id: "card-2",
    holderName: "Helen Xu",
    number: "4727856245678921",
    expiry: "08/21",
    cvv: "774",
    status: "active",
    network: "visa",
    availableBalance: 1860,
  },
  {
    id: "card-3",
    holderName: "Ganesh Babu",
    number: "5177856245679022",
    expiry: "04/22",
    cvv: "665",
    status: "frozen",
    network: "mastercard",
    availableBalance: 1024,
  },
];

export const transactions: Transaction[] = [
  {
    id: "txn-1",
    cardId: "card-1",
    merchant: "Hamleys",
    date: "2020-05-20",
    amount: 150,
    currency: "SGD",
    category: "shopping",
    description: "Refund on debit card",
  },
  {
    id: "txn-2",
    cardId: "card-1",
    merchant: "Hamleys",
    date: "2020-05-20",
    amount: -150,
    currency: "SGD",
    category: "travel",
    description: "Charged to debit card",
  },
  {
    id: "txn-3",
    cardId: "card-1",
    merchant: "Hamleys",
    date: "2020-05-20",
    amount: -150,
    currency: "SGD",
    category: "food",
    description: "Charged to debit card",
  },
  {
    id: "txn-4",
    cardId: "card-2",
    merchant: "Uber Rides",
    date: "2020-05-18",
    amount: -32,
    currency: "SGD",
    category: "travel",
    description: "Charged to debit card",
  },
  {
    id: "txn-5",
    cardId: "card-3",
    merchant: "Amazon",
    date: "2020-05-12",
    amount: -420,
    currency: "SGD",
    category: "shopping",
    description: "Charged to debit card",
  },
];

export const comments: Comment[] = [
  {
    id: "c-1",
    author: "Ravi Jha",
    role: "Guest",
    date: "2022-04-29",
    message: "Hello,\ntest message",
    avatarColor: "#C4C4C4",
  },
  {
    id: "c-2",
    author: "Ganesh Babu",
    role: "",
    date: "2021-12-14",
    message: "kl",
    badge: 1,
    avatarColor: "#00C5DC",
    edited: true,
  },
  {
    id: "c-3",
    author: "aa",
    role: "Guest",
    date: "2021-10-09",
    message: "aa",
    avatarColor: "#C4C4C4",
  },
];
